version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=users-auth
    volumes:
      - users-auth-pgdata:/var/lib/postgresql/data

volumes:
  users-auth-pgdata: